name: Swift

on: 
  push:
    branches: 
    - "*"
  pull_request:
    branches: 
    - "*"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  macOS:
    runs-on: macOS-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: swift build
      
  linux:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    container:
      image: swift:5.1.3
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update -qq
        apt-get install -q -y tzdata libssl-dev zlib1g-dev
    - name: Build
      run: swift build
